GET http://localhost:3001/api/v1/vehicle?brand=honda&seats=4&uppercase=false

###

GET http://localhost:3001/api/v1/vehicle/122

###

GET http://localhost:3001/api/v1/vehicle/jeep/4/seats/7

###

POST http://localhost:3001/api/v1/vehicle

###

PATCH http://localhost:3001/api/v1/vehicle/50

###

PUT http://localhost:3001/api/v1/vehicle/75

###

DELETE http://localhost:3001/api/v1/vehicle/100
