GET http://localhost:3001/api/v1/vehicle?brand=honda&seats=4&uppercase=false

###

GET http://localhost:3001/api/v1/vehicle/122

###

GET http://localhost:3001/api/v1/vehicle/jeep/4/seats/7

###

POST http://localhost:3001/api/v1/vehicle
Content-Type: application/json

{
    "brand": "Toyota",
    "model": "Corola",
    "color": "Prata",
    "year": 2022,
    "seats": 4,
    "doors": 4
}

###

POST http://localhost:3001/api/v1/vehicle
Content-Type: application/x-www-form-urlencoded

brand=Volkswagen&model=Tiguan&color=Branco&year=2023&seats=5&doors=4

###

POST http://localhost:3001/api/v1/vehicle
Content-Type: multipart/form-data; boundary=--WebKitFormBoundary2Q3W

----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="brand"

Volkswagen
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="model"

Tiguan
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="color"

Branco
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="year"

2023
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="seats"

5
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="doors"

4
----WebKitFormBoundary2Q3W
Content-Disposition: form-data; name="cover"; filename="2023-volkswagen-tiguan.png"
Content-Type: image/png

< C:/Users/jorge/Downloads/2023-volkswagen-tiguan.png
----WebKitFormBoundary2Q3W--

###

PATCH http://localhost:3001/api/v1/vehicle?id=50
Content-Type: application/json

{
    "brand": "Jeep",
    "model": "Compass",
    "color": "Branco",
    "isEletric": false,
    "year": 2023,
    "engine": 2.0,
    "features": ["Ar Condicionado", "Direção Elétrica"]
}

###

PUT http://localhost:3001/api/v1/vehicle/A7A5

###

DELETE http://localhost:3001/api/v1/vehicle/100
